# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-23 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='webPractice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tableName', models.CharField(max_length=30)),
                ('key', models.CharField(max_length=20)),
                ('value', models.IntegerField(default=0)),
            ],
        ),
    ]
